AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'vendor/bundle/**/.*'
    - '.bundle/**/*'
    - 'bin/lolcommits'
    - 'lolcommits.gemspec'

# don't agree with this one, can lead to long lines that are harder to parse
Style/IfUnlessModifier:
  Enabled: false

inherit_from: .rubocop_todo.yml
