sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  # stub mplayer/ffmpeg so it looks like they are installed
  - mkdir -p ~/bin
  - touch ~/bin/mplayer ~/bin/ffmpeg
  - chmod +x ~/bin/mplayer ~/bin/ffmpeg
  - export PATH=~/bin:$PATH
  - git --version

notifications:
  slack:
    secure: BkGsQOYMJqW55j94S1QwmR17BkwuTIULKVhwzRdnv37BvVcC17y9KLMo8NH+bcao36XZx9DukXcTyaDQc6tCSlFEbG/FcPUJM8bx9EWjHUoGVg1KdpVu/nVHu+GKosrB41lM3nfJWCnF0TOSnmTXU+bV8Pwkij+L5X+gNyAT2Ns=

deploy:
  provider: rubygems
  api_key:
    secure: Y7FFOMDahITtHYRV3UQAw+BA2JbqoArN/Ii9PUTU6RaLmTIvpZBzqtvR3r8ah3SdXNh0Cx10gVf0pRc6HXKTNQdwMWCkOQwukAb+9kLDKFxl3x+w4X2u6yWmtsyNMTWK1gF4hEF1IHnsdg2dYEoFfE2M5bHex85ND/Q6820sPa8=
  gem: lolcommits
  on:
    tags: true
    repo: lolcommits/lolcommits

env:
  global:
    - CC_TEST_REPORTER_ID=6170a470c98ca6537e4c19848d4d4201dbb1eff1960ba7fee1a278d91b9fb1f1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build
